#!/bin/bash

# Variable to store whether or not to auto-start
auto_start=1

while true; do
    # Use yad to display the form
    yad_output=$(yad --title "StormOS Welcome" --form --columns=2 --width=480 --height=100 --text="Welcome to <b>StormOS</b> this will help get you started. Keep in mind that this app will be replaced after install with the post-install version." --image=$HOME/stormos.png  \
    --field="<b>StormOS Installer Normal</b>":fbtn "sh -c 'sudo -E /usr/bin/calamares'" \
    --field="<b>Visit StormOS Site</b>":fbtn "xdg-open https://stormos-linux.com" \
    --field="<b>StormOS Installer Debug</b>":fbtn "xfce4-terminal -e 'sudo -E /usr/bin/calamares -D6'" \
    --field="<b>StormOS ReadMe</b>":fbtn '/usr/local/bin/readme' \
    --field="Auto Start":chk "$auto_start" \
    --button=Exit:1 --button="Apply:0" --separator=",")

    # Get the return value of the yad command
    return_value=$?

    # Check if the Exit button was clicked
    if [ $return_value -eq 1 ]; then
        break
    fi
done
