#!/bin/bash
iso_name="GenesisOS"
iso_label="GENESISOS"
iso_publisher="GenesisOS Team"
iso_application="GenesisOS Live/Rescue"
iso_version="$(date +%Y.%m.%d)"
install_dir="arch"
buildmodes=('iso')

bootmodes=('bios.syslinux' 'uefi.systemd-boot')

arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
file_permissions=(
  ["/etc/shadow"]="0:0:400"
  ["/root"]="0:0:750"
  ["/root/.automated_script.sh"]="0:0:755"
  ["/root/.gnupg"]="0:0:700"
  ["/usr/local/bin/choose-mirror"]="0:0:755"
  ["/usr/local/bin/Installation_guide"]="0:0:755"
  ["/usr/local/bin/livecd-sound"]="0:0:755"
  ["/usr/local/bin/postinstall.sh"]="0:0:755"
  ["/usr/local/bin/readme"]="0:0:755"
  ["/usr/local/bin/launcher"]="0:0:755"
  ["/etc/gshadow"]="0:0:400"
  ["/etc/shadow"]="0:0:400"
  ["/usr/local/bin/trust.sh"]="0:0:755"
  ["/etc/skel/.config/autostart/calamares.desktop"]="0:0:755"
  ["/etc/skel/.config/autostart/NetworkManager.desktop"]="0:0:755"
  ["/etc/skel/.config/autostart/autoi.desktop"]="0:0:755"
  ["/etc/skel/.config/autostart/welcome.desktop"]="0:0:755"
  ["/etc/skel/Desktop/calamares.desktop"]="0:0:755"
  ["/usr/bin/wifi-connection.sh"]="0:0:755"
  ["/usr/local/bin/fm10"]="0:0:755"
  ["/usr/local/bin/term5"]="0:0:755"
  ["/usr/local/bin/launcher"]="0:0:755"
  ["/usr/local/bin/hyper8"]="0:0:755"
  ["/usr/local/bin/autoi"]="0:0:755"
  ["/usr/local/bin/eco_menu"]="0:0:755"
  ["/usr/local/bin/eco_sys"]="0:0:755"
  ["/usr/local/bin/eco_rec2"]="0:0:755"
  ["/usr/local/bin/eco_nvidia"]="0:0:755"
  ["/usr/local/bin/eco_pac"]="0:0:755"
)